# Generated by Django 5.0.1 on 2024-03-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen',
            field=models.ImageField(default='articulo/articulo_sin_imagen.jpg', upload_to='articulo/'),
        ),
    ]
