# Generated by Django 5.0.1 on 2024-02-23 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='stock',
        ),
    ]
