# Generated by Django 5.0.2 on 2024-02-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_articulos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='cantidad_entrada',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salidas',
            name='cantidad_salida',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
