# Generated by Django 5.0.1 on 2024-03-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_articulos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articulo/'),
        ),
    ]
