# Generated by Django 5.0.1 on 2024-03-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_articulos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='imagen',
        ),
        migrations.AddField(
            model_name='articulos',
            name='imagen_articulo',
            field=models.ImageField(default='articulo/articulo_sin_imagen.jpg', upload_to='articulo/'),
        ),
    ]
