# Generated by Django 5.0.1 on 2024-03-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_articulos_imagen_articulos_imagen_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen_articulo',
            field=models.ImageField(blank=True, null=True, upload_to='articulo/'),
        ),
    ]
