# Generated by Django 5.0.1 on 2024-03-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_rename_imagen_articulo_articulos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen',
            field=models.ImageField(blank=True, default='articulo/articulo_sin_imagen.jpg', null=True, upload_to='articulo/'),
        ),
    ]
