# Generated by Django 5.0.2 on 2024-03-06 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_donacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_donacion', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fecha_donacion', models.DateField(auto_now_add=True)),
                ('estado_donacion', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('entregado', models.BooleanField(default=False)),
                ('Articulos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.articulos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.tipo_donacion')),
            ],
        ),
    ]
