# Generated by Django 5.0.2 on 2024-02-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donaciones',
            name='cantidad_donacion',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
