# Generated by Django 5.0.1 on 2024-02-11 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usuario', models.CharField(max_length=100, unique=True, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('nombres', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('tipo_documento', models.IntegerField(blank=True, choices=[(1, 'CC'), (2, 'TI'), (3, 'CE')], default=1, null=True)),
                ('documento', models.CharField(blank=True, max_length=12, null=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Activo'), (2, 'Inactivo')], default=1, null=True)),
                ('rol', models.IntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Veterinario'), (3, 'Adoptante')], default=3, null=True)),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='ImagenPerfil', verbose_name='Imagen de perfil')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
