# Generated by Django 5.0.2 on 2024-02-16 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_rename_adopciones_adopcion_historialmedico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialmedico',
            old_name='fecha_adopcion',
            new_name='fecha_historial',
        ),
    ]
