# Generated by Django 5.0.2 on 2024-02-16 00:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_rename_fecha_adopcion_historialmedico_fecha_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
