# Generated by Django 5.0.2 on 2024-02-16 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0005_adopcion_updated_historialmedico_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_proceso', models.IntegerField(choices=[(1, 'Aceptada'), (2, 'En Tramite'), (3, 'Rechazada')], default=1)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('solicitud', models.FileField(upload_to='solicitudesAdopcion/', verbose_name='Solicitud Adopción')),
                ('estado_solicitud', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mascota.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.IntegerField(choices=[(1, 'Fase 1'), (2, 'Fase 2'), (3, 'Fase 3'), (4, 'Fase 4'), (5, 'Fase 5'), (6, 'Fase 6')], default=1)),
                ('estado_fase', models.IntegerField(choices=[(1, 'Aceptada'), (2, 'En Tramite'), (3, 'Rechazada')], default=1)),
                ('fecha_seguimiento', models.DateField(auto_now_add=True)),
                ('estado_seguimiento', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default=1)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('solicitud_adopcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mascota.solicitudadopcion')),
            ],
        ),
    ]
