# Generated by Django 5.0.2 on 2024-02-22 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0006_solicitudadopcion_seguimientoadopcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='estado_mascota',
            new_name='estadoRegistro',
        ),
    ]
