# Generated by Django 5.0.1 on 2024-02-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0007_rename_estado_mascota_mascota_estadoregistro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mascota/'),
        ),
    ]
