# Generated by Django 5.0.2 on 2024-03-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0008_alter_mascota_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientoadopcion',
            name='fase',
            field=models.IntegerField(choices=[(1, 'Fase 1'), (2, 'Fase 2'), (3, 'Fase 3'), (4, 'Terminado')], default=1),
        ),
    ]
